export class IndicadorSectorialResponse {
    ACUM_PER?: string;
    ADECUACION?: boolean;
    AVG_META_ALCANZADA?: string;
    AVG_META_PLANEADA?: string;
    CICLO?: number;
    CLARIDAD?: boolean;
    DEFINICION_META?: string;
    DESCRIPCION_OBJETIVO?: string;
    DOF_DESCRIPCION_LB?: string;
    DOF_DESCRIPCION_META?: string;
    ENFOQUE_INDICADOR?: string;
    ENFOQUE_RES?: string;
    FUENTE_INFORMACION?: string;
    LB_COLOR?: string;
    MALCANZADA_COLOR?: string;
    MAX_META_ALCANZADA?: string;
    MAX_META_PLANEADA?: string;
    META?: number;
    META_ALCANZADA?: string;
    META_COLOR?: string;
    METODO_CALCULO?: string;
    MIN_META_ALCANZADA?: string;
    MIN_META_PLANEADA?: string;
    MONITOREABILIDAD?: boolean;
    NIVEL_DESAGREGACION?: string;
    NOMBRE_META?: string;
    PERIODICIDAD?: string;
    PERTINENCIA?: boolean;
    PORCENTAJE_AVANCE?: string;
    PORCENTAJE_COLOR?: string;
    RAMO?: string;
    RELEVANCIA?: boolean;
    TENDENCIA?: string;
    TIPO?: string;
    UDM?: string;
    VALOR_LB?: string;
    CAMBIO_TEXTO?: string;
    TIPO_INDICADOR_GRAFICA?: string;

    constructor() {
        this.ACUM_PER = '';
        this.ADECUACION = false;
        this.AVG_META_ALCANZADA = '';
        this.AVG_META_PLANEADA = '';
        this.CICLO = 0;
        this.CLARIDAD = false;
        this.DEFINICION_META = '';
        this.DESCRIPCION_OBJETIVO = '';
        this.DOF_DESCRIPCION_LB = '';
        this.DOF_DESCRIPCION_META = '';
        this.ENFOQUE_INDICADOR = '';
        this.ENFOQUE_RES = '';
        this.FUENTE_INFORMACION = '';
        this.LB_COLOR = '';
        this.MALCANZADA_COLOR = '';
        this.MAX_META_ALCANZADA = '';
        this.MAX_META_PLANEADA = '';
        this.META = undefined;
        this.META_ALCANZADA = '';
        this.META_COLOR = '';
        this.METODO_CALCULO = '';
        this.MIN_META_ALCANZADA = '';
        this.MIN_META_PLANEADA = '';
        this.MONITOREABILIDAD = false;
        this.NIVEL_DESAGREGACION = '';
        this.NOMBRE_META = '';
        this.PERIODICIDAD = '';
        this.PERTINENCIA = false;
        this.PORCENTAJE_AVANCE = '';
        this.PORCENTAJE_COLOR = '';
        this.RAMO = '';
        this.RELEVANCIA = false;
        this.TENDENCIA = '';
        this.TIPO = '';
        this.UDM = '';
        this.VALOR_LB = '';
        this.CAMBIO_TEXTO = '';
        this.TIPO_INDICADOR_GRAFICA = '';
    }
}